services:
  php:
    image: php:8.2-fpm
    build:
      context: php
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./data:/var/www/html/data

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf